### ISSUE TITLE
'Unranked' subspecies were not merged properly into xCOL 

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#100]
There are several subspecies that were not merged properly into the xCOL even though some other subspecies from the same genus and source were merged correctly:

Here is the example of genus Mycotretus: 
 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/d1a6b69e-936e-4f03-a01a-4236f435a2ec)

Looking for the genus Mycotretus in the XCOL-2023-10-26 found this: 

https://www.dev.checklistbank.org/dataset/271349/classification?taxonKey=5W6T
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/80610e58-fdf0-490d-87e5-6a146ea18181)

Besides, other species were merged more than once, depending on the number of subspecies related: 
https://www.dev.checklistbank.org/dataset/271349/classification?taxonKey=3349c2de-e025-4ab9-89a8-194d32b30a32

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/33fc9e9a-2539-4bbd-9e79-6e528c968725)

Or were merged more than once, one with author and one without author: 
https://www.dev.checklistbank.org/dataset/271349/classification?taxonKey=e4aabe0e-9a9d-49eb-a400-0492fc8c77bd
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/21d4882c-c96f-4963-a85b-fdda55028edc)

**Comment by mdoering** [comment]
Mycotretus discipennis subsp. conductus Kuhnt, 1910
for example exists twice:
https://www.dev.checklistbank.org/dataset/271349/taxon/~4Gik
https://www.dev.checklistbank.org/dataset/271349/taxon/~4Glb

**Comment by mdoering** [comment]
I believe all the did not merge problems are due to missing name matches! There was a very hard to spot bug in the rematch function that prevented most matches to persist.

**Comment by DianRHR** [comment]
> And occurs twice in the Plazi source, once accepted, once as a synonym: https://www.dev.checklistbank.org/dataset/56536/duplicates?limit=50&rank=subspecies

Looking at the article, found that _Mycotretus discipennis conductus_ Kuhnt, 1910 **[as a variety]** is synonym of Mycotretus deyrollei Crotch, 1876 AND synonym of  Mycotretus discipennis conductus Kuhnt, 1910 (subspecies) . 
So ... the original info is that there is the same name trinomial with different rank, but also ... the "variety" points to different accepted names.   These kind of errors are out of our hands.

**Comment by DianRHR** [comment]
> Besides, other species were merged more than once, depending on the number of subspecies related: https://www.dev.checklistbank.org/dataset/271349/classification?taxonKey=3349c2de-e025-4ab9-89a8-194d32b30a32

same as reported in [#87 ](https://github.com/CatalogueOfLife/xcol/issues/87)

**Comment by DianRHR** [comment]
The cases of Peloploca and Pelonema are solved and properly merged. 

The case of subspecies of Mycotretus is not possible to confirm until we merge Plazi datasets. 

However, some genus are merging below the kingdom level because the original source either doesn't include higher taxonomy or it is different from the base COL. Some of these cases are also generating duplicates: 

Example: Genus Cribraria
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/af6cb422-3b44-405f-9564-bf4714a18182)
was merged below Fungi (merged from Brazilian Flora), even though it was already in the [baseCOL   ](https://www.checklistbank.org/dataset/298754/taxon/C8RTJ) below Cribrariales | Cribrariaceae and in both cases have the same author. Besides, all the species merged below Cribaria (at the lingdom level) are duplicated as well. 

A possible solution for this cases could be to modify the code  considering: avoid merging if it's the same genus (and author) within the same kingdom, but with different higher taxonomy, descendants could be merged if not present already.

**Comment by mdoering** [comment]
Still happening in 5th July: https://www.checklistbank.org/dataset/299581/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=Cribraria&sortBy=taxonomic

See also https://github.com/CatalogueOfLife/xcol/issues/87

**Comment by mdoering** [comment]
might be solved with https://github.com/CatalogueOfLife/backend/commit/71560f62c2e0b0879f7d71bbad89ba76f7631856

Need to verify in next xrelease on 19th July
